### ISSUE TITLE
Peer reviews

### ISSUE THREAD

**Issue by BigDGW** [eJourn-al/eJournal#203]
Students should be able to review the journals from eachother. Aditionally, a teacher would have to grade only journal entries that have passed this review.

**Comment by Larspolo** [comment]
Bumping. Julia vroeg hierom, en het lijkt Maarten en mij wel goed om deze kant op te gaan na de assessment uitbreiding.

**Comment by Larspolo** [comment]
Julia is graag betrokken bij de technische implmentatie van deze feature. Graag wil ze dat we Brit en haar benaderen na het opzetten van een technisch document waarin we de flow zichtbaar hebben, en kijken hoe dat eruit ziet

**Comment by Larspolo** [comment]
Moved to epic
