### ISSUE TITLE
Selection template fields

### ISSUE THREAD

**Issue by BigDGW** [eJourn-al/eJournal#212]
There should be a template field that allows the user to choose one of multiple predefined options, for example using dropdowns and radio buttons.

**Comment by Airgetfrog** [comment]
![image](https://user-images.githubusercontent.com/29678823/46563797-cdd25a80-c903-11e8-93bf-cc54b169ff9b.png)
@engelhamer any suggestions for the appearance on the selection options? Or would you rather it be a selection input instead of radio?

**Comment by engelhamer** [comment]
I think a dropdown would be more logical, this is more of a multiple choice question (which could be another field type!).
