### ISSUE TITLE
Assignment deadline & availability

### ISSUE THREAD

**Issue by BigDGW** [eJourn-al/eJournal#216]
Assignments should have deadlines and should stop being available after a certain date. Availability would then determine whether the user can still post entries.

#196 should also provide these details from LTI.

**Comment by engelhamer** [comment]
A start and end date can also be retrieved via LTI.

**Comment by BigDGW** [comment]
unlock date, deadline and lock date are retrieved through LTI, but i need a place to store them so they can be used.

**Comment by engelhamer** [comment]
It would be nice if the deadline and lock dates were fixed nodes. That way the timeline will always have an ending (complementing #269).

**Comment by Airgetfrog** [comment]
In that case, would it be a good idea to display the fact that an assignment is yet to be unlocked/already locked in that respective node (and have it be selected automatically if it is)? Seems like a nice way to do it, just displaying those 3 nodes when locked.

Also, what should be done about points possible and max points? Points possible can easily be used to create the final deadline node, but what then should we do about max points.

**Comment by engelhamer** [comment]
Max_points should be omitted alltogether. But we'll make that a separate issue.
