### ISSUE TITLE
Remove assignment from course without deleting assignment from all courses

### ISSUE THREAD

**Issue by Airgetfrog** [eJourn-al/eJournal#250]
It is currently impossible to remove an assignment from a course without deleting it entirely. Possible fixes might be adding a remove button on assignments cards in courses (and deleting automatically if it was the only course using that assignment), or a similar solution in the course editor screen.

**Comment by Airgetfrog** [comment]
![image](https://user-images.githubusercontent.com/29678823/43396163-feb0dcb8-9400-11e8-8460-d53b2ef1b501.png)

Does this look ok to you @engelhamer? Only problem is that it currently runs into trouble if both a progress bar and remove should be displayed (the user is a student with course edit rights).

**Comment by engelhamer** [comment]
Should be fine. I reckon only few students will be able to edit courses
anyways.

Op ma 30 jul. 2018 14:05 schreef Hendrik Huang <notifications@github.com>:

**Comment by Airgetfrog** [comment]
As it turns out this functionality exists, it is simply labeled as delete while editing the assignment. Potentially confusing as edits in this screen are carried across all courses while deleting is local to the current course.

**Comment by engelhamer** [comment]
A confirmation stating something like 'are you sure you want to remove this assignment from course XXX' (where 'XXX' can be retrieved using the course ID in the router path) should be fine then.

**Comment by engelhamer** [comment]
Since deletion of assignments is a course-level permission, it might be better to move the delete button after all.
