### ISSUE TITLE
All permission changes to default roles are applied to first Course

### ISSUE THREAD

**Issue by Airgetfrog** [eJourn-al/eJournal#253]
Creating and editing custom roles works as expected, _except_ when names are duplicated.

I suspect it is to do with the `db_role = Role.objects.filter(name=role['name'])` line (132 in update.py), which presumably finds all roles matching the same name, of which then only the first appearing is edited (which can be in an entirely different course). This also causes creation of roles with duplicate names in another course to fail (or more precisely, causes the permission in the other course to be updated).

**Comment by engelhamer** [comment]
Are roles in no way connected to courses right now? That seems strange. Adding a cID to a role should be fine.

**Comment by Airgetfrog** [comment]
Roles have a foreign key to a course, however I do not currently know how to filter by database id at the same time. Looks like I'll have to look into django database modeling.

**Comment by engelhamer** [comment]
Alright. Sounds like an error in the API then.

Op do 2 aug. 2018 15:14 schreef Hendrik Huang <notifications@github.com>:
