### ISSUE TITLE
Tutorial for first-time users

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#278]
# Feature request

## Description
Some advanced functionality (e.g. the format editor) of the application is quite complicated, and therefore rather confusing for first-time users. Adding a step-by-step tutorial for these pages when a user first visits them would be helpful.

## User story
As a user I want a step-by-step tutorial on how to use more advanced, complicated features.

## User interface
[Vue-tour](https://github.com/pulsardev/vue-tour) should provide for some good functionality for this.

**Comment by Airgetfrog** [comment]
Is this being worked on?

**Comment by engelhamer** [comment]
I will incorporate this along with some changes in the format/timeline structure this weekend.
