### ISSUE TITLE
Removing a user from a course throws an error

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#286]
# Bug report

## Expected Behavior
Removing a user from a course should throw no error

## Actual Behavior
Removing a user from a course throws a 
`Error in render: "TypeError: Cannot read property 'toLowerCase' of undefined"`
Because the user still exists client side somewhere.

## Steps to Reproduce the Problem
1. Remove a user from a course

**Comment by Larspolo** [comment]
I cannot replicate this bug. I think this has been resolved with the rest-api merge?

**Comment by engelhamer** [comment]
Seems to be fixed indeed.
