### ISSUE TITLE
Course creation throws an error

### ISSUE THREAD

**Issue by Airgetfrog** [eJourn-al/eJournal#306]
# Bug report

## Expected Behavior
A course should be created with relevant values and no error.

## Actual Behavior
An error is thrown but the course is still created with the correct values.
![image](https://user-images.githubusercontent.com/29678823/45257184-4b0cbd00-b3a2-11e8-9f55-92f5d4ae1649.png)

## Steps to Reproduce the Problem
1. Attempt to create a course

**Comment by engelhamer** [comment]
Opening the newly created course also seems to go wrong: No content is displayed,

**Comment by engelhamer** [comment]
Fixed in #305.
