### ISSUE TITLE
Format editor sometimes fails to save

### ISSUE THREAD

**Issue by Rickyboy320** [eJourn-al/eJournal#312]
# Bug report

## Expected Behavior
Format editor should save properly.

## Actual Behavior
Format editor sometimes fails to save, after 'normal' user behaviour.
It is still uncertain what behaviour exactly causes this, but I will do some additional testing when I have the time.

## Steps to Reproduce the Problem
1. Open Format Editor
2. Add a lot of nodes and edit a lot (uncertain step, needs investigation)
3. Save the format - it may fail.

**Comment by Airgetfrog** [comment]
The format editor also sometimes gives an 'unsaved progress' notification without the user having changed anything. Perhaps you could investigate this too?

**Comment by Larspolo** [comment]
For me this occurred with a bad_request caused by the following code:
```        try:
            templates, presets, unused_templates, max_points, removed_presets, removed_templates \
                = utils.required_params(request.data, "templates", "presets", "unused_templates", "max_points",
                                        "removed_presets", "removed_templates")
        except KeyError:
            return response.keyerror("templates", "presets", "unused_templates", "max_points", "removed_presets",
                                     "removed_templates")```

**Comment by engelhamer** [comment]
The false 'unsaved progress' originates from the available template cards if I recall correctly.

**Comment by mjvkeulen** [comment]
Has this been replicated since?

**Comment by engelhamer** [comment]
This indeed happens sometimes and the snippet lars posted above is involved. However, I have only ever encountered this in the development enviroment. Specifically after some changes that affect the current format edit page while it's open. I therefore think that this behaviour is a side effect of the live reload functionality and not an implementation problem. Shall we close this issue?

**Comment by Rickyboy320** [comment]
It just failed again, after unknown reasons (did the same thing after and then it worked).
So issue is still present, even on deploy, but still unknown what causes it.

**Comment by engelhamer** [comment]
This is getting spooky.

**Comment by Airgetfrog** [comment]
Seems like a good idea for now to put a timeout on the frontend editor lock, that way if it fails the user can at least try again. Might want to test to make sure it doesn't keep failing though. If it turns out that it keeps failing or once we have some extra time someone can try to reproduce/fix it at that point?
