### ISSUE TITLE
Increase font size in Journal

### ISSUE THREAD

**Issue by Rickyboy320** [eJourn-al/eJournal#317]
# Feature request

## Description
Larger font size in the journal. The current font is extremely small, while this being the most important part of the page. Even the Progress node card is extremely small. We have a lot of whitespace, we should utilize this.
Some fields, like the PDF suddenly have increased font size, which looks inconsistent and ugly.

## User story
As an user I want to more easily make out distinct characters in my journal.

## User interface
Here's an example of inconsistent font size:
![image](https://user-images.githubusercontent.com/3754047/45434312-6b908c00-b6ae-11e8-9128-c1d468cb62cc.png)
I would suggest using the size (or a bit smaller) of the PDF field althroughout. We have more than enough space, even when a lot is typed.

Here's an example of a lot of whitespace, while on laptops (or probably beamers too) it is quite hard to read.
![image](https://user-images.githubusercontent.com/3754047/45434405-a7c3ec80-b6ae-11e8-9c25-2f69831a8566.png)

**Comment by engelhamer** [comment]
The inconsistency will be fixed in #309, and was already mentioned in #315. I personally do not think that we should increase the font size, since we now use a size of 1em, the default size which adapts to the device. Furthermore all headings have been sized accordingly.
