### ISSUE TITLE
Institute edit page

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#326]
# Feature request

## Description
There needs to be an institute edit page where the institute can set their name, icon, contact email?

## User story
Is you are a superuser you need to be able to click on the edit button in the homepage

**Comment by engelhamer** [comment]
Wait, isn't this already available? (Except for the email address)

**Comment by engelhamer** [comment]
Apparently it has been removed along the way. My bad.

**Comment by engelhamer** [comment]
Fulfilled by the admin panel.
