### ISSUE TITLE
Image field display does not shrink correctly on hide

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#336]
# Bug report

## Expected Behavior
After toggling an image display, the entire field should collapse correctly.

## Actual Behavior
![image](https://user-images.githubusercontent.com/39912610/45594619-6416fe80-b99e-11e8-8a2e-c44c792d1813.png)

**Comment by engelhamer** [comment]
This has to do with the fact that the image itself contains a v-if. In case the image has been loaded this will be there, but when you toggle back only the visibility will changes.

**Comment by engelhamer** [comment]
Was fixed in #389.
