### ISSUE TITLE
Redesign of the add node and save buttons in the assignment edit page

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#343]
# Feature request

## Description
Redesign of the add node and save buttons in the assignment edit page

## User story
As a teacher you want to add a node by pressing a button in the timeline, not at the bottom in the main-content part

## User interface
![image](https://user-images.githubusercontent.com/11822478/45644832-0af2bc00-babf-11e8-80c7-1b58366ad207.png)
underneath this image, add an add node that adds a new node

![image](https://user-images.githubusercontent.com/11822478/45644864-1e058c00-babf-11e8-986b-f544fe6d0740.png)
Change this save format button to a FAB that only appears when there are changes to be saved

**Comment by engelhamer** [comment]
I really like the FAB suggestion! 👍

**Comment by Rickyboy320** [comment]
What’s a FAB?

**Comment by engelhamer** [comment]
A (floating action button)[https://material.io/design/components/buttons-floating-action-button.html].
