### ISSUE TITLE
Description of assignment not loading

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#344]
# Bug report

## Expected Behavior
When going to the AssignmentEdit page, you want to see the description of the assignment.

## Actual Behavior
The description of the assignment is empty, only appears after a reload/move back and forth from 2 nodes.

## Steps to Reproduce the Problem
1. login
2. https://ejourn.al/Home/Course/5/Assignment/5/Format

**Comment by JowehL** [comment]
Is this bug already fixed, I can't reproduce the bug anymore on the develop branch and the link in the bug report is a link to deployment.

**Comment by engelhamer** [comment]
This has not yet been fixed. It has to do with timing issues related to the API call that fetches the description, which takes longer on production (i.e. a remote server) than the development environment.
