### ISSUE TITLE
Redesign of the "stackable templates" feature

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#345]
# Feature request

## Description
Redesign of the "stackable templates" feature. The current implementation is unclear.

## User story
 Currently to enable a student to submit multiple versions of a template, as teacher you have to put the templated on "enabled" status.

Suggested improvement:
Add another node to the timeline where you can select the "stackable templates"

## User interface
Screenshot or description of user interface changes
![image](https://user-images.githubusercontent.com/11822478/45645153-ed722200-babf-11e8-8899-35b4e494a019.png)
These "enabled" buttons are unclear

**Comment by engelhamer** [comment]
I don't think a node in the timeline is very logical for this. A teacher should only be concerned with preset nodes and progress checks there. I do have some ideas in mind that also have to do with #278 that fit in nicely with this though.

**Comment by engelhamer** [comment]
Will be finalized in #278
