### ISSUE TITLE
Grading an entry crashes with unknown error

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#347]
# Bug report

## Expected Behavior
Grade an entry

## Actual Behavior
Unknown error. It still grades, but crashes someone midway.

## Steps to Reproduce the Problem
1. login as teacher
2. https://ejourn.al/Home/Course/2/Assignment/1/Journal/1?sort=sortUsername
3. grade
4. save

**Comment by engelhamer** [comment]
This does not happen on the current develop branch. Maybe an outdated issue, or something that has to do with the deploy?

**Comment by Rickyboy320** [comment]
I cannot reproduce either. Closing until someone is able to reproduce.
