### ISSUE TITLE
Points -> Total points

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#349]
# Feature request

## Description
Points -> Total points

## User interface
![image](https://user-images.githubusercontent.com/11822478/45645498-e3045800-bac0-11e8-9e6f-01c7213c7931.png)
to
![image](https://user-images.githubusercontent.com/11822478/45645503-e992cf80-bac0-11e8-9d1a-79ab8b463315.png)

**Comment by engelhamer** [comment]
I personally think that this looks pretty bad. Reading it doesn't sound smooth.
I would suggest changing the title of this section to 'Journal progress' to reflect that this concerns the entire journal's progress, instead of this.
