### ISSUE TITLE
Automatically scrolls down on large entries

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#350]
# Bug report

## Expected Behavior
To not scroll down when viewing an entry

## Actual Behavior
Scrolls down when viewing an entry (caused by the autofocus on the rich text editor)

## Steps to Reproduce the Problem
1. go to an entry that is larger then your screen

**Comment by engelhamer** [comment]
So, this is not actually a problem with entries but rather with the rich text editor. Let's never auto focus on that ever again!
