### ISSUE TITLE
Add users to a course needs to be changed

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#355]
# Feature request

## Description
A teacher should be able to get the whole list of all the student, they should only be able to add them by student id/name

## User interface
![image](https://user-images.githubusercontent.com/11822478/45646444-a38b3b00-bac3-11e8-90ac-878d3e922e2b.png)
This should be just an input field iso a list of all users

**Comment by engelhamer** [comment]
So the list should be replaced with some indication that the user should type something.
