### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#359]
# Feature request

## Description
Notification system has to be implemented
Some random dutch ideas:
  - Optie per Cursus of studenten mogen reageren, en als docenten/TAs of je daar dan notificatie van wilt (per week/maand?).
  - Student krijg een notificatie als de docent nagekeken heeft. Met directe link naar die pagina. maar misschien niet 3 mailtjes als een TA er tegelijk 3 nagegekeken heeft. bachen? daily digest
  - TA/Teacher bericht als student iets nieuws heeft gepost? maar dan alleen naar de groep coordinator?

**Comment by engelhamer** [comment]
This is a duplicate issue. See #213.
