### ISSUE TITLE
A negative grade is a valid grade

### ISSUE THREAD

**Issue by Rickyboy320** [eJourn-al/eJournal#365]
# Bug report

## Expected Behavior
Negative grades should be rejected (both front-sided and back-sided)

## Actual Behavior
They are happily accepted, and work properly with all calculations.

## Steps to Reproduce the Problem
1. Attempt to edit someone's grade
2. Input a negative grade
3. Save

This may be an intended feature (to deduct points for whatever reason), but it looks unintended (as confirmed by Engel).

**Comment by libre-man** [comment]
You have to watch out with this, as with normal LTI passback only grades between zero and 1.0 are accepted.
