### ISSUE TITLE
Stop using `is` for checking equality

### ISSUE THREAD

**Issue by libre-man** [eJourn-al/eJournal#368]
In many checks `is` is used to check equality between things that are not `True`, `None` or `False`, such as integers. This is not guaranteed to work in Python (as this compares object identity, not if two objects are the same), for example (on my machine):
```python
>>> a = int('2342345')
>>> b = int('2342345')
>>> a is b
False
```

Use `==` for checking if two objects are the same, and use `is` to check if an object is `None`.

**Comment by mjvkeulen** [comment]
Appreciate the input, good catch!
