### ISSUE TITLE
asynchronous profile pictures

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#375]
# Feature request

## Description
The profile pictures need to load asynchronous to improve speed on especially the assignment overview page where there is a large list of students that all load in with their profile picture

**Comment by Archifer** [comment]
What do you mean exactly by loading asynchronous? Do you only mean it for the front-end?, for example show only the first n students with then a button of load n more, or how do you exactly see this enhancement?

**Comment by engelhamer** [comment]
Current alle pictures are loaded along with the page, which introduces a
delay. Loading the pictures asynchronously (independent of the page itself)
this should make the page feel quicker. This does not require any
alterations to the amount of cards shown.

>

**Comment by Archifer** [comment]
Ooh oke I was thinking in another way, but this makes way more sense thanks!

**Comment by Airgetfrog** [comment]
Is this being handled? If not, could someone give a clear overview of the issue (and relevant code)? From what I've seen it doesn't look to be an issue (profile pictures are loaded from url when student cards render, student cards render once filteredjournals exists, filteredjournals only exists when assignmentAPI get returns, i.e. the rest of the page data already exists)?

**Comment by Larspolo** [comment]
![image](https://user-images.githubusercontent.com/11822478/46581231-64526900-ca35-11e8-98cd-f5fd6f520ba8.png)
The profile picture is only a url when its: the default profile picture, or connected to a canvas user. Else you get this b64 string back that takes can easily be half a MB. As a solution I would suggest to store the profilepictures in the user folder iso as a b64 string in the db

**Comment by Larspolo** [comment]
Closed in file rework
