### ISSUE TITLE
No error toast on Internal Server Error on password recovery

### ISSUE THREAD

**Issue by Stanbroek** [eJourn-al/eJournal#388]
# Bug report

## Expected Behavior
Expected a toast to pop up when password recovery fails.

## Actual Behavior
Nothing happens, but in f12 it says it returned `500 Internal Server Error`.

## Steps to Reproduce the Problem
1. Display a toast when something goes wrong like a `500 Internal Server Error`.

![image](https://user-images.githubusercontent.com/11822478/46086263-048fce80-c1a8-11e8-9242-8021b667bcbd.png)

**Comment by engelhamer** [comment]
Cannot reproduce this locally. Maybe the email password has not been configured correctly on the deploy environment? @Larspolo

**Comment by Larspolo** [comment]
This issue exists is when the username and password or the mail (in the deployed version) of `src/django/VLE/settings/email.py` are not correct.

After changing the password, it now works again

![image](https://user-images.githubusercontent.com/11822478/46095327-8689f280-c1bc-11e8-825d-ffef211e9e0b.png)

**Comment by engelhamer** [comment]
Yup, just what I thought. I reckon this does not require a user-facing toast.
