### ISSUE TITLE
Prettier landing page

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#395]
# Feature request
## Description
The current landing page (page that is displayed when a user is not logged in) was flanked together in order to show something on a demo. It contains old screenshots and barely any text. We should update our landing page to better reflect the state and assets of the application!

## User story
A shiny and attractive landing page!

## User interface
Will figure this out once I start working on this.

**Comment by Larspolo** [comment]
Didnt see this issue, and that you were assigned to it. Closing as it was fixed in #432

**Comment by Larspolo** [comment]
Some more suggestions:
- superusers can edit (some parts of) this page in a rich text field
- when deployed a message of where its deployed and maybe a links to the connected Canvases or the organization itself

**Comment by engelhamer** [comment]
Changelogs etc. will appear elsewhere as discussed.
