### ISSUE TITLE
Stop using first and last name for users

### ISSUE THREAD

**Issue by libre-man** [eJourn-al/eJournal#402]
# Bug report
The names of users are split up into first and last name, however this is not a valid assumption for many people.

## Expected Behavior
There should be only one name field, something like `full_name`.

## Actual Behavior
The name of the user is split up.

**Comment by engelhamer** [comment]
Do you mean that we exclude people with only a first name by this (or special cases like 'van Keulen' as a last name)?

**Comment by libre-man** [comment]
The distinction simply doesn't make sense. There are people without a last/last name, you can read more about it [here](https://www.w3.org/International/questions/qa-personal-names). I don't see the reason for the distinction, so I think it should simply be removed.
