### ISSUE TITLE
Format and Course Edit ask confirmation upon leaving after saving

### ISSUE THREAD

**Issue by Airgetfrog** [eJourn-al/eJournal#415]
# Bug report

## Expected Behavior
Saving changes and leaving should peave without prompt.

## Actual Behavior
A browser prompt is shown.

## Steps to Reproduce the Problem
1. Edit format/course details.
2. Save.
3. Attempt to leave.

**Comment by engelhamer** [comment]
This is due tot the save operation immediately triggering the watchers on
the template pool.

**Comment by engelhamer** [comment]
Sure, but try removing the watchers and evertthing will work as expected.
