### ISSUE TITLE
Deadline updating doesn't work

### ISSUE THREAD

**Issue by Jeroentetje3** [eJourn-al/eJournal#418]
# Bug report

## Expected Behavior
When editing a deadline of a node in the format editor, the save icon shows up.

## Actual Behavior
When editing a deadline of a node in the format editor, the save icon doesn't show up.

## Steps to Reproduce the Problem
1. Login as a teacher
2. Go to a assignment and edit it.
3. Click on one of the nodes on the left.
4. Edit the deadline.
5. See that the save icon doesn't show up in the bottem right corner.

# Feature request

## Description
Make it so that the change of the deadline in a node is detected and triggers the save button to come up.

**Comment by engelhamer** [comment]
Same goes for the description of an assignment. The change detection is malfunctioning on that page, see #415.

**Comment by engelhamer** [comment]
Fixed.
