### ISSUE TITLE
Description field for preset entries

### ISSUE THREAD

**Issue by Rickyboy320** [eJourn-al/eJournal#419]
# Feature request

## Description
Predefined entries should have a description field. This makes it possible to reuse a template (such as a PDF template that is generic for 'uploading pdfs'), while keeping the freedom of explaining the reasoning for the entry. Currently this is only achievable by making a template for each entry.

A concrete example is the following:
An assignment (portfolio) requires us to upload multiple PDFs, each with different their own reasoning and deadline. Currently we cannot make one template that fits all these scenarios, because the first deadline needs a different description than the others, instead we have to make a template that embeds the new description.

## User story
As an user, I want to add a description to a preset-entry (entrydeadline) node such that I do not have to redefine templates for minor description changes.

**Comment by engelhamer** [comment]
Good Idea!
