### ISSUE TITLE
Complete max user storage handling 

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#455]
**Describe the solution you'd like**
We require an institute-wide configuration setting, which indicates the maximum storage space per user in order to avoid abuse. 
This check encompasses the following:

- Total content data of entries
- Total user-file size
- Profile picture
 
Possibly allowing for an individual setting per item as well.

**User story**
As an institute, I want to be able to limit user storage through an intuitive menu.

**User interface**
Ideally, this is done through an institute-wide settings menu front-end. Which will require dedicated backend handling of the settings. Messing around with constants in the development and production files is not ideal. However, this solution could be a temporary fix.

**Comment by libre-man** [comment]
Don't create a front-end setting for this. You will probably always want an instance per institution and the max storage size per user will be set during the creation of the instance not by the administrator at some later date (you will need to upgrade certain aspects of your sever when increasing the storage size).
