### ISSUE TITLE
Groups from VLE

### ISSUE THREAD

**Issue by BigDGW** [eJourn-al/eJournal#485]
**Describe the solution you'd like**
The groupname that is gotten from datanose should be used to put the user in the same group

**User story**
I want to be in the same group in ejournal as in the VLE

**Comment by libre-man** [comment]
I talked to some people that are in connection with the Canvas team and they stated that in this year Canvas should bring a feature that will make LTI and groups actually work together. So I would wait with this feature for a bit :)
