### ISSUE TITLE
Field descriptions in the format editor should scale to content.

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#505]
**Describe the solution you'd like**
Field descriptions in the format editor should scale to content.

**Comment by engelhamer** [comment]
I think a rich text editor (#470) Will be large enough on itself, and we should definitely not have them scale up. Those things can rise to enormous size, and please keep in mind that all is still contained in a drag-and-drop card. The latter would become impossible to handle!

**Comment by mjvkeulen** [comment]
It would handle perfectly, except with more scrolling. All of which is related to the provided content, no user will complain about scrolling too much when they are reviewing the spelling of their long description text.

**Comment by mjvkeulen** [comment]
I can see working with a max height on the text area to accommodate low-width devices.

**Comment by engelhamer** [comment]
But drag-and-dropping something that is *larger* than the modal makes no sense in my opinion..

**Comment by engelhamer** [comment]
Users can resize the field if they so desire anyways.

**Comment by mjvkeulen** [comment]
Talking from the rich-text editor perspective I take it?

**Comment by engelhamer** [comment]
Regardless the type: standard textareas can be resized as well.

**Comment by mjvkeulen** [comment]
This is not an appropriate solution for our userbase. The icon generally displayed to handle this in the bottom right is not used by teachers in this fashion. 
Simply setting a height (can be capped) to fit the description will solve this and is far more user friendly.

**Comment by mjvkeulen** [comment]
However for this use case #470 will be sufficient, so I will close this issue. The rich text editor will provide sufficient scrolling space.

**Comment by engelhamer** [comment]
Fine by me, its size just shouldn't skyrocket 😄
