### ISSUE TITLE
Excess preset entry nodes

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#507]
**Describe the bug**
Random preset entry deadline nodes appear in a journal where a user has added entries via the add node.

**To Reproduce**
1. Post an entry as a user using the add node.

**Expected behavior**
No preset entry deadline nodes added.

**Screenshots**
The added nodes have no details, date or entry. Additionally they mess up the node indexing when clicked on, resulting in console warnings.

![screenshot_20181105-184513__01](https://user-images.githubusercontent.com/39912581/48016101-fa5bdb00-e12a-11e8-8270-8588d0f922b8.jpg)

**Smartphone (please complete the following information):**
 - Device: Oneplus 5
 - OS: OxygenOS 5.1.5 (Android Oreo 8.1.0)
 - Browser: Chrome
 - Version: 70.0.3538.80

**Comment by engelhamer** [comment]
Cannot reproduce this locally. Was this a migration issue after all @Larspolo?

**Comment by engelhamer** [comment]
Appears to have been a migration issue.

**Comment by engelhamer** [comment]
Appears not to have been a migration issue. Still occurs in production.

**Comment by Larspolo** [comment]
This may be (partially) due to a validation bug that is fixed in #722. We need to revisit this bug if it continues to be a problem after that PR is deployed.
