### ISSUE TITLE
Dealine nodes visual indication in timeline

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#522]
**Describe the solution you'd like**
Deadline nodes in the timeline should show a visual indication of whether that specific condition has been met. Currently, they are simply always displayed as orange.

**User story**
As a user, I desire a visual indication of whether a deadline node has been met in the timeline.

**Comment by engelhamer** [comment]
We decided not to do this yesterday (in #377).

**Comment by mjvkeulen** [comment]
Ah good catch, I am of the opinion we should reopen #377 then. During my DS seminar, I received feedback that this was perceived as not user-friendly, and I a tend to agree.
