### ISSUE TITLE
LTI course not ready screen

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#527]
**Describe the solution you'd like**
- A dedicated screen to this scenario, explaining the situation in a lighthearted way.
- Notification with sufficient context so the eJournal team can take action as well.
- Notification to the staff member if known (preferably in a non spammy fashion).

**User story**
As a student start LTI launch without the corresponding course having been set up on eJournal by the teacher yet. Currently, a 404 with a hint in subtext is displayed, I want to be reassured I did nothing wrong. Tell me to contact my teacher to get things in order.

**Comment by engelhamer** [comment]
An email should be sent to the teacher of the course (in case their details are known) to let them know they need to take action and students are following the unconfigured link. With a cooldown to prevent spam.
