### ISSUE TITLE
LTI: Link to existing assignments displaying no, or limited options.

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#528]
**Describe the bug**
As a teacher, when I am linking a VLE assignment to eJournal, the link to existing Assignment option is showing either no or limited options.

**To Reproduce**
1. Go to the Canvas LTI launch to eJournal
2. Click on `Link to existing Account`
3. Click on **A**: `Create new Course` or **B**: `Link to existing Course`.
4. Click on `Link to existing Assignment`

**Expected behavior**
- Following **A**, 4 should show all existing Assignments the user is privileged to link with.
- Following **B**, 4 should show all existing Assignments the user is privileged to link with as well. However, a clear distinction is desired which Assignments are already part of the just chosen Course to link with. Currently, only the assignments already part of the chosen course are displayed.

**Comment by Larspolo** [comment]
It would also be nice if you get forwarded when there are no assignments that you can connect to

**Comment by engelhamer** [comment]
This is related to #685.

**Comment by mjvkeulen** [comment]
fixed in #707

**Comment by mjvkeulen** [comment]
fixed in #707
