### ISSUE TITLE
Format editor description does not show on initial load.

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#551]
**Describe the bug**
Format editor description does not always show on initial load, often a page refresh is required to show the description.

**To Reproduce**
1. Edit the format of an assignment.
2. The description won't always load.
3. Refresh the page, the description now shows.

**Expected behavior**
The assignment description should always show, even in the format editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/39912610/51495975-8393bd00-1dbe-11e9-947a-fc979911ead5.png)

**Comment by Larspolo** [comment]
Fixed
