### ISSUE TITLE
Soft deadlines

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#565]
**Describe the solution you'd like**
Now all the deadlines are hard deadlines, and users get an exclamation mark when submitting too late/not submitting at all. Sometimes a teacher wants to create soft deadlines that indicate where a student needs to be, but not necessarily create a visual wrongdoing when not achieving the deadline. 

Another method of implementing soft deadlines would be the use of due and lock dates per node. Here passing the due date, would only give a small visual indication, and passing the lock date, would block the possibility to create an entry.

Another option would be to include both options, which makes it more customizable, but also harder to know what does what.

**Comment by engelhamer** [comment]
I'd go with a unlock-due-lock structure like for assignments.
