### ISSUE TITLE
Add "send" to the comment post button

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#578]
**Describe the bug**
Publish after grade for comments does not work. When I publish the grade, the comment will remove the checkbox for publish after grade, but it does not publish the comment itself. When I reload the page, the comment has disappeared.

**Additional context** 
Browser: Chromium
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Comment by engelhamer** [comment]
Publishing a comment along with the grade still requires the comment to be sent. This should become clearer.
