### ISSUE TITLE
Points to achieve in Student ToDo card

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#584]
**Describe the solution you'd like**
As a student, I would like to see how many points I still need to achieve before the next deadline. Now it just displays when the upcoming deadline is, but an extra amount would be nice

Edit: this is only possible for deadlines with as goal an amount of points. For other deadlines, an indication on what kind  of deadline it is, would also be nice

**User Interface**
![image](https://user-images.githubusercontent.com/11822478/52823747-57661600-30b6-11e9-93c1-038d63b865a9.png)

**Comment by engelhamer** [comment]
The next deadline need not necessarily be a progress node so this won't always hold.
