### ISSUE TITLE
Upcoming deadline notification

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#600]
**Describe the solution you'd like**
A notification when a student has an upcoming deadline in their journal that is not yet finished.

This should be checked
- One week in advance
- One day in advance

**User interface**
A call to action email with a link to the corresponding entry.

**Related issue**
This is part of #213.

**Comment by Larspolo** [comment]
Has still some issues

**Comment by Larspolo** [comment]
Fixed in #723
