### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#609]
**Describe the solution you'd like**
Key bindings for actions such as...
- Saving a grade (publish and non-publish)
- Sending a comment (directly and after grade)
- Going one node forward and backward in the timeline
- Viewing the next and precious journal

**User story**
Press some combination of keys to execute actions faster.

**User interface**
An info dialog showing the bindings.

**Comment by Larspolo** [comment]
Closing in favour of another issue
