### ISSUE TITLE
Ignore capitalisation in usernames

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#610]
**Describe the solution you'd like**
It makes no sense that different capitalisation can yield different unique usernames. This is also quite dangerous, since e.g. a capital letter i could be used to imposter a lowercase L: 'I' versus 'l'. All usernames should be made lowercase.

**Comment by Larspolo** [comment]
same goes for email. I would also suggest moving this up in priority

**Comment by engelhamer** [comment]
Requiring users to provide a case sensitive email address when requesting a password recovery is also not very friendly..
