### ISSUE TITLE
Back end assignment format validation

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#612]
**Description**
Assignment format validation happens only in the front end, and is not enforced in the back end. This way a teacher *could* introduce things like due dates before unlock dates *if they make changes to the local JavaScript*. It would be even better to enforce the front end validation server-sided as well.

Note that no security concerns are related to this issue. This is merely for increased consistency.

**Comment by engelhamer** [comment]
I think the scope of this should be bigger: back-end format validation as a whole.
