### ISSUE TITLE
You can have multiple assignments with the same name under 1 course

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#674]
**Describe the solution you'd like**
You can have multiple assignments with the same name under 1 course. This should not be possible as this makes it unclear which assignment is which 

**User interface**
Current interface:
![image](https://user-images.githubusercontent.com/11822478/57179106-3a9ddb00-6e7a-11e9-8397-a756617217af.png)

Here you cannot distinguish between the different assignment

**Comment by engelhamer** [comment]
Adding some visual indication to distinguish them should suffice.
