### ISSUE TITLE
Support Canvas speedgrader

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#678]
**Describe the solution you'd like**
Our current cross-referencing policies are very strict and do not allow eJournal to be embedded in an iframe in the Canvas speedgrader. Since teachers would like to use this functionality of the LMS some sort of whitelist option is desired.

**Comment by mjvkeulen** [comment]
Move away from `X_FRAME_OPTIONS` and move to CSP2 (https://django-csp.readthedocs.io/en/latest/)

**Comment by mjvkeulen** [comment]
This issue is reported as not fixed on our FNWI instance according to Robert van Wijk
