### ISSUE TITLE
Better looking spinner

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#712]
**Describe the solution you'd like**
The current spinner when loading (journals, from LTI to eJournal etc.) is not that good looking. It would be nice if users would be greeted with a nicer loading icon

**Comment by engelhamer** [comment]
> The current spinner when loading (journals, from LTI to eJournal etc.) is ~~not that good looking.~~ already awesome, but it would be nice if users would be greeted with a nicer loading icon.

😉
