### ISSUE TITLE
Student preview 

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#718]
**Describe the solution you'd like**
A method for a teacher to view an assignment as if they were a student. This would give a clearer view of how the assignment is set-up, and check if it's correct.

**User story**
Login as teacher,
go to an assignment edit page,
press a button that says "student view"
be able to view the assignment as a student

**Comment by engelhamer** [comment]
Ideally this would be accessible through e.g. the Canvas course student view

**Comment by mjvkeulen** [comment]
Support for the LMS student view, allowing for a (fake/temp) student launch to eJournal would make this a fully-fledged feature.

**Comment by engelhamer** [comment]
Like I said :wink:
