### ISSUE TITLE
Format editor save button appears when clicking around on entrynodes

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#719]
**Describe the bug**
Format editor save button appears when clicking around on entrynodes

**To Reproduce**
1. Go to an assignment editor page
2. Click some entrynodes without editing them
4. See save button appear

**Expected behavior**
No save button when you are not editing

**Comment by engelhamer** [comment]
This is due to Flatpickr unwantedly changing the value of empty unlock, due and lock dates, thus triggering the detected changes and save button.
