### ISSUE TITLE
Send reply to feedback in same mail thread as user confirmation

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#742]
**Describe the solution you'd like**
When receiving feedback, we send a confirmation with the given feedback to the user. Another email is sent to us, with some more context information. These mails should be sent in the same email thread, so we can get back to the user as a reply on their confirmation email.

**Comment by engelhamer** [comment]
This is not possible using the current Django mail configuration: email clients decide how mails are grouped by their own criteria.
