### ISSUE TITLE
Add more flexibility to the timeline in a journal

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#746]
**Describe the solution you'd like**
The timeline can grow to a pretty large size, making it hard to find what you're looking for. It would be nice to collapse parts of the timeline, or use tabs to split is up a bit more.

**Comment by mjvkeulen** [comment]
Engel: Tabs will scale better (horizontally no space issue) over a tree as navigation.

**Comment by engelhamer** [comment]
Check also portfolio doc
