### ISSUE TITLE
Make UI stretch less on wide screens

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#750]
**Describe the solution you'd like**
The UI becomes very wide on wide screens (e.g. 21:9). See below:

![image](https://user-images.githubusercontent.com/39912581/66256172-70c5ea80-e78b-11e9-8cfb-9f114fddd0dd.png)

This makes text harder to read and looks a bit clumsy overall.

**Comment by Larspolo** [comment]
@engelhamer is this fixed in the upcoming UI branch

**Comment by engelhamer** [comment]
> @engelhamer is this fixed in the upcoming UI branch?

Yes
