### ISSUE TITLE
Assignments only for specific groups (cohorts)

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#759]
**Describe the solution you'd like**
As a teacher, I would like to create assignments that are only available for a specific group (Canvas section). This makes it possible to add assignments on cohort basis, whereafter they will only see their track with their own deadlines.

FPS wants to use this

**User story**
Add students from 1 cohort to a Canvas section.
Make an assignment for only that eJournal group (the cohort).
Copy templates and everything from previous year.
Done :)
Now all students from the new cohort can only see that assignment, while still being in the same Canvas bachelor page with all the other students from all the other courses.

**Comment by engelhamer** [comment]
This is a pretty major design change that will make assignment setup and LTI connections much more complicated.
