### ISSUE TITLE
Copy assignment causes 500 error for existing journals

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#778]
**Describe the bug**
Upon changing an assignment  by copying its structure from another assignment, loading an existing journal for the updated assignment causes a 500 error (traced back to the `get_nodes` function).

**To Reproduce**
1. Fill the preset database
2. As the `Teacher`, copy the assignment structure from 'Logboek' into 'Colloquium'
3. Try to load a student journal

**Expected behavior**
Existing journals should obviously remain functional.

Maybe we should not allow copying once an assignment has been created.

**Comment by Larspolo** [comment]
Fixed in #771
