### ISSUE TITLE
Uploading an image through the rich text editor's browse button does not work

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#788]
**Describe the bug**
The rich text editor contains a button in the toolbar to upload an image from the user's device. Upon clicking it the file browser appears and a file can be selected, however the selected image is not inserted into the rich text field. Drag-and-dropping from e.g. Nautilus does seem to work.

**To Reproduce**
1. Create a new entry with a rich text field
2. Click on the image button at the top of the editor
3. Click on the browse icon
4. Select an image
5. Observe that it is not inserted

**Expected behavior**
The image should be inserted into the rich text field.

**Comment by mjvkeulen** [comment]
Is being worked on under tinymce-update
