### ISSUE TITLE
Warning dialogue for unsupported browsers

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#802]
**Describe the solution you'd like**
We use functionality (the `srcdoc` attribute on iframes, see #799) that is not fully supported by browsers like Edge. A warning indicating preferred browsers for an optimal viewing experience would be a welcome addition.

**Comment by engelhamer** [comment]
Especially (older) internet explorer browser functionality is lacking. Warning those who still (dare to) use it would not hurt.
