### ISSUE TITLE
Default unpublish assignment after copy

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#806]
**Describe the solution you'd like**
When copying an assignment, the publish state is currently also copied. It is possible to change the publish state just after copying, however. This seems odd. It would make sense to add a publish button to the copy modal.

**Comment by Larspolo** [comment]
Or default to the unpublished state after copying?

**Comment by engelhamer** [comment]
Should correspond to what the LTI setting is then.

**Comment by Larspolo** [comment]
This will be less of an issue when group-assignments is merged. Teacher will be able to unpublish as long as there are no entries.

**Comment by engelhamer** [comment]
Unpublishing is fine since the first visit via LTI will publish if needed anyways.
