### ISSUE TITLE
Default entry grade per assignment

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#835]
**Describe the solution you'd like**
A teacher would like grading to be a swift process. Ideally, an entry grade in an assignment has a default value, so that the grading process can be reduced with another action.

For most of our use cases a default grade of one would suffice, but ideally this can be configured at the assignment level.

**Comment by engelhamer** [comment]
I think that if a teacher would prefer a default grade rather than something more specific they would be better off with sufficient/insufficient instead of a number for each entry.

**Comment by Larspolo** [comment]
Does the "per template" approach now satislfy this? Then it can be cloed

**Comment by engelhamer** [comment]
I think so!
