### ISSUE TITLE
Minimal test student group association

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#845]
**Problem**
A `test student` is enrolled in all sections on the Canvas side by default, this can result in a major group overload for Courses which are set up according to a Bachelor course page structure. Test students can be (re)created on-demand, currently this means all according groups will also be (re)created, even if these groups were manually removed by a teacher.

**Proposed solution**
A test student should be assigned to or create no group(s), unless the course holds assignments which are `assign to` a specific group. In this case, the test student should be added to these groups in order to remain compatible.

**Comment by engelhamer** [comment]
I'd say: automatically keep the test student added to any group that also
contains real students. That way it will always show up regardless of group
filters being applied or not, yet won't flood the filter list.

**Comment by engelhamer** [comment]
Will be addressed by updating #846 instead.
