### ISSUE TITLE
Improve assignment editor

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#859]
**Describe the solution you'd like**
The assignment editor is a bit too complicated for intuitive use. It should become easier to create and maintain assignment settings without further introduction, so teachers can get started on their own straight away. 

Some changes:
- Separate 'unlimited' templates from preset only templates (it is not intuitively clear what they mean)
- Improve the template editor (drag and drop sometimes bugs) (another issue [Zube #1101](https://zube.io/ejourn-al/ejournal/c/1101) )
- Make it more clear where errors are eJourn-al/eJournal#840
~~- Make it more clear when changes are saved for templates (all is saved at once upon clicking the save FAB, it can be unintuitive to click the cross on a template modal while changes have been made)~~
~~- Copy templates from other assignments eJourn-al/eJournal#310 ~~
~~- Clearly indicate that new preset needs to be added to the timeline [Zube #1477](https://zube.io/ejourn-al/ejournal/c/1477) ~~

**Comment by Larspolo** [comment]
Joelle wil maximum aantal keren 1 template gebruiken

**Comment by engelhamer** [comment]
Eerst Portfolio design document afwachten

**Comment by Larspolo** [comment]
Moved this to triage again for re-evaluation

**Comment by mjvkeulen** [comment]
Would this then be a mini epic? Or should we just move unlimited vs limited seperation into another issue and close this?
