### ISSUE TITLE
Identically named groups in lists cannot be distinguished

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#869]
**Describe the bug**
See screenshot. 2 groups are called "staff", one for each course. Teacher will never know for which groups it is assigning the assignment to.

**Expected behavior**
indication for the groups of the course that is selected

**Screenshots**
![image](https://user-images.githubusercontent.com/11822478/76163392-fb997f80-6145-11ea-824e-f40b0184d8ec.png)

**Comment by engelhamer** [comment]
How do you mean 'one for each course'?

**Comment by Larspolo** [comment]
Two different courses havingthe same group name (staff in this example). Would be nice to see from which course these groups come from.

**Comment by engelhamer** [comment]
So this is an assignment with a link to two courses then.

**Comment by Larspolo** [comment]
That, but can also be for an assignment with two groups with the same name.

**Comment by engelhamer** [comment]
Should not have been closed (since the commit dit _not_ fix it.

**Comment by engelhamer** [comment]
Actually I think that the 'assign to' part should only concern a single course, though this problem may still persist. Example: one course has no groups but another has, but they share the same assignment. Then you would want to be able to assign to some groups first, but in the later course assign to everyone (i.e. no 'assign to' group selected).
