### ISSUE TITLE
Sandboxed iframes do not size images correctly on Firefox

### ISSUE THREAD

**Issue by mjvkeulen** [eJourn-al/eJournal#884]
**Describe the bug**
When submitting an image as the content of a sandboxed iframe, the first render is clipped vertically.

**To Reproduce**
1. Use Firefox
2. Go to the format editor
3. Select a template
4. Pass an image into a rich text field
5. Click on preview
6. Observe vertically clipped render of image
7. Toggle edit and preview, observe correctly loaded image

**Screenshots**
First render:
![image](https://user-images.githubusercontent.com/39912610/76997864-5015d980-6954-11ea-9437-41225ffe586c.png)

Second render:
![image](https://user-images.githubusercontent.com/39912610/76997885-5d32c880-6954-11ea-8e1e-e0fb3ce3febf.png)

**Desktop**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version 74.0

**Comment by engelhamer** [comment]
Can you reproduce this outside of the template editor?
