### ISSUE TITLE
Rich text editor converts some images to b64

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#924]
**Describe the bug**
Images that are too large in size of have a too long file name are still accepted by the rich text editor, and converted to b64.

**To Reproduce**
1. Go to any rich text field (e.g. comment)
2. Drag and drop an image with a very long name (over 255 chars preferably) or too large size
3. See error about length or size
4. Observe that the image is still saved

**Expected behavior**
No conversion should occur and the image should be discarded.

**Screenshots**
![image](https://user-images.githubusercontent.com/39912581/79261475-305ccd00-7e90-11ea-9f08-b6403a855c13.png)

![image](https://user-images.githubusercontent.com/39912581/79261214-cba17280-7e8f-11ea-9392-378cedd5d568.png)

**Comment by Larspolo** [comment]
Is this bug still present?

**Comment by engelhamer** [comment]
Yes:

**Comment by Larspolo** [comment]
Agree with the prio's, @mjvkeulen can you take a look at this?
