### ISSUE TITLE
A "nothing todo" display when all todo's are done

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#934]
**Describe the solution you'd like**
A "nothing todo" display when all todo's are done. Even better would be to also add a section of "global" stats: stats about entries not graded in your group specifically 

Something like this in the ToDo section if everything is graded / filled in / whatever other todo stuff there is
![image](https://user-images.githubusercontent.com/11822478/79741461-966aa980-8301-11ea-88ae-a15992c03e14.png)

**Comment by engelhamer** [comment]
> [...] Even better would be to also add a section of "global" stats: stats about entries not graded in your group specifically

What do you mean with this? We have some stats that are sensitive to the group filter at hand on the assignment page already (which I think is a suitable location for this).

**Comment by Larspolo** [comment]
> What do you mean with this? We have some stats that are sensitive to the group filter at hand on the assignment page already (which I think is a suitable location for this).

An option to not only see the todo of your own groups, but also all users in the assignment

**Comment by engelhamer** [comment]
> An option to not only see the todo of your own groups, but also all users in the assignment

Ah good, has been implemented in #935 👍
