### ISSUE TITLE
File feedback attached to comment

### ISSUE THREAD

**Issue by Larspolo** [eJourn-al/eJournal#939]
**Describe the solution you'd like**
Being able to submit (mutliple) files as feedback on an entry. This is most useful when wanted to share your annotated PDF.

PDF (or other file) as comment

**Comment by Larspolo** [comment]
High because I think it would greatly improve the experience for feedback in documents. Which might be used during PSE

**Comment by mjvkeulen** [comment]
With a variable number of files as feedback, the medium workload seems under-budgeted.

**Comment by Larspolo** [comment]
Test
