### ISSUE TITLE
Don't use assignment serializer for TODO cards

### ISSUE THREAD

**Issue by engelhamer** [eJourn-al/eJournal#952]
**Describe the solution you'd like**
The assignment serializer is currently used for the todo cards as well. This means that for simply displaying the title of an assignment and the next deadline as follows:

![image](https://user-images.githubusercontent.com/39912581/81476259-451f4d00-9211-11ea-8328-b1768cdd14d6.png)

we send the following data:

```[ { "id": 1, "deadline": { "date": "2020-05-23T02:24:45", "name": "8/10 points" }, "journal": 4, "stats": { "average_points": 4.5 }, "course": { "id": 1698, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 2", "abbreviation": "PAV2", "startdate": "2019-09-01", "enddate": "2022-07-31", "active_lti_id": null, "assignment_lti_id_set": [] }, "courses": [ { "id": 1697, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 1", "abbreviation": "PAV1", "startdate": "2018-09-01", "enddate": "2021-07-31", "active_lti_id": null, "assignment_lti_id_set": [] }, { "id": 1698, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 2", "abbreviation": "PAV2", "startdate": "2019-09-01", "enddate": "2022-07-31", "active_lti_id": null, "assignment_lti_id_set": [] } ], "course_count": 2, "journals": null, "is_group_assignment": false, "active_lti_course": null, "lti_courses": null, "name": "Logboek", "description": "<p>This is a logboek for all your logging purposes</p>", "is_published": true, "points_possible": 10, "unlock_date": null, "due_date": null, "lock_date": null, "active_lti_id": null, "lti_id_set": [], "remove_grade_upon_leaving_group": false, "can_set_journal_name": false, "can_set_journal_image": false, "can_lock_journal": false, "author": 7, "format": 1, "assigned_groups": [] }, { "id": 3, "deadline": { "date": null, "name": null }, "journal": null, "stats": { "average_points": 0 }, "course": { "id": 1698, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 2", "abbreviation": "PAV2", "startdate": "2019-09-01", "enddate": "2022-07-31", "active_lti_id": null, "assignment_lti_id_set": [] }, "courses": [ { "id": 1698, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 2", "abbreviation": "PAV2", "startdate": "2019-09-01", "enddate": "2022-07-31", "active_lti_id": null, "assignment_lti_id_set": [] } ], "course_count": 1, "journals": null, "is_group_assignment": true, "active_lti_course": null, "lti_courses": null, "name": "Group Assignment", "description": "<p>This is a group assignment. This is purely for testing group assignment stuff.<br/>Initialized with student and student2 in 1 journal and student3 in another.</p>", "is_published": true, "points_possible": 10, "unlock_date": null, "due_date": null, "lock_date": null, "active_lti_id": null, "lti_id_set": [], "remove_grade_upon_leaving_group": false, "can_set_journal_name": false, "can_set_journal_image": false, "can_lock_journal": false, "author": 7, "format": 3, "assigned_groups": [] }, { "id": 2, "deadline": { "date": "2020-05-13T14:59:25.769", "name": "Mentorgesprek" }, "journal": 13, "stats": { "average_points": 4.5 }, "course": { "id": 1697, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 1", "abbreviation": "PAV1", "startdate": "2018-09-01", "enddate": "2021-07-31", "active_lti_id": null, "assignment_lti_id_set": [] }, "courses": [ { "id": 1697, "lti_linked": false, "name": "Portfolio Academische Vaardigheden - Cohort 1", "abbreviation": "PAV1", "startdate": "2018-09-01", "enddate": "2021-07-31", "active_lti_id": null, "assignment_lti_id_set": [] } ], "course_count": 1, "journals": null, "is_group_assignment": false, "active_lti_course": null, "lti_courses": null, "name": "Colloquium", "description": "<p>This is the best colloquium logbook in the world</p>", "is_published": true, "points_possible": 10, "unlock_date": null, "due_date": null, "lock_date": null, "active_lti_id": null, "lti_id_set": [], "remove_grade_upon_leaving_group": false, "can_set_journal_name": false, "can_set_journal_image": false, "can_lock_journal": false, "author": 7, "format": 2, "assigned_groups": [] } ]```

which to me seems like a bit too much. Note that this is for students, teachers receive even more unneeded data.

I think some speedup could be achieved here.

**Comment by Larspolo** [comment]
"Add a TODO serializer, specially designed for TODO cards"
